Algoritmo "semnome"

Var
// Seção de Declarações das variáveis 
// TIPOS DE DADOS
//caractere - texto
nome: caractere

valor: real
//inteirp - "valor redondo"
idade : inteiro
//logico - verdadeioro e falso, boolear
ligado  : logico

// regras de variavel
// 1 - não pode palavras dedicadas
// 2 - não pode caractere especiais
// 3 - não pode acentos e cedilha
// 4 - não pode começar com numero / só o numero
//5 - nao pode espacos vazios
//   * camel case  - nomeComposto
//   * snake case - nome_Composto
//   * upper case - NOMECOMPOSTO(maisculo)
//   * lower case - nomecomposto(minusculo)



Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("olá mundo")
escreval ("estou aprendendo a programar")
escreva ("3 + 12")
Fimalgoritmo