Algoritmo "Brazil street"

Var
opcao : inteiro


Inicio
escreval ("*******************")
escreval ("****Brazil Street****")
escreval ("---------------------")
escreval ("1) Tenis - R$ 450,00")
escreval ("2) Camiseta - R$ 150, 00 ")
escreval ("3) Short -  R$ 100, 00")
escreval ("4) Blusa de frio - R$ 500,00")
escreval ("5) Conjunto - R$ 2000,00")
escreval ("6) FINALIZAR COMPRA")
escreval ("7) SAIR")
leia(opcao)
escolha (opcao)
caso 1
 escreval("comprando Tenis")
 caso 2
 escreval("comprando Camiseta")
 caso 3
 escreval("comprando Short")
 caso 4
 escreval("comprando Blusa de frio")
 caso 5
 escreval("comprando conjunto")
 caso 6
 escreval("selecionou finalizar")
 caso 7
 escreval("selecionou sair")
 outrocaso
 escreval ("erro ! opção inválida")
 fimescolha

Fimalgoritmo