Algoritmo "semnome"

Var
senha ,  senhaCadastrada : caractere
Inicio
senhaCadastrada <- "0711"
//condicional
// + somar
// - subtrair
// * multiplicar
// / dividir
// % modulo resto da divisao
// ** elevado

// OPERADORES REÇACIONAIS
// = IGUALDADE ( == EM OUTRAS LINGUAGENS )
// > MAIOR
//<  MENOR
// >= MAIOR OU IGUAL
// <= MENOR OU IGUAL
//<> DIFERENÇA ( ! = EM OUTRAS LINGUAGENS)
escreval ("digite a senha: ")
leia(senha)
se (senha=senhaCadastrada) entao
escreval ("Senha correta!")
senao
escreval ("senha incorreta!")
fimse
Fimalgoritmo