Algoritmo "AULA6"

Var
contador : inteiro
repete : caractere
condicao : logico

Inicio
condicao <- verdadeiro
   enquanto (condicao) faca
   escreval ("Repete S/N")
   leia(repete)
   se (repete = "s")  entao
       condicao <- verdadeiro
   senao
     condicao <- falso
   fimse
   fimenquanto
// PROCEDIMENTO
procedimento teste()
var
data : caractere
inicio
 escreval("FUNCIONOU!!")

 data<- "19/02/2026"
 escreval(data)
fimprocedimento
teste()
Fimalgoritmo






