Algoritmo "semnome"

Var
idade:inteiro


Inicio
escreval ("qual a sua idade")
leia(idade)
se (idade<=5) e (idade>=7) entao
   escreval("infantil A")
fimSe

se (idade<=8) e (idade>=11) entao
   escreval("infantil B")
fimSe

se (idade<=12) e (idade>=13) entao
   escreval("Juvenil A")
fimSe

se (idade<=14) e (idade>=17) entao
   escreval("Juvenil B")
fimSe

se (idade<=18) entao
   escreval("Adultos")
fimSe
Fimalgoritmo