Algoritmo "DOIS NUMEROS"


Var

valor1: inteiro
valor2 :inteiro


Inicio

escreval ("qual o valor desejado?")
   leia (valor1)
escreval ("digite o segundo valor")
   leia (valor2)
                se (valor1 = valor2)entao
escreval ("numeros iguais")
                se (valor1 > valor2)entao
escreval ("primeiro numero maior")
                se (valor1 < valor2)entao
escreval ("segundo valor maior")

fimse
fimse
fimse
Fimalgoritmo